# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/console-cli"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/console-daemon"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/desktop-winforms"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/desktop-winui"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/desktop-wpf"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/spa-blazor-wasm"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/web-api-obo-client"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/web-api-obo-user"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/web-api"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/web-app-aspnet"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/web-app-blazor-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    directory: "/xplat-maui"
    schedule:
      interval: "daily"
    labels:
      - "dependabot"
      - "dependencies"
