name: Verify Dependabot Update (.NET)

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'  # Specify the .NET version you're using (e.g., 5.x, 6.x, 7.x)

      # Find all .csproj files in the subdirectories and loop over them
      - name: Restore, Build, and Test All Projects
        run: |
          for project in $(find . -name '*.csproj'); do
            echo "Processing project: $project"
            dotnet restore $project
            dotnet build $project --no-restore --configuration Release
            dotnet test $project --no-build --configuration Release
          done
